package controllers

object LangCodes {

  // ISO 639 Language Codes
  val TwoPartLangCodesMap = Map(
  	"aa" -> List("aar","Afar"),
	"ab" -> List("abk","Abkhazian"),
	"af" -> List("afr","Afrikaans"),
	"ak" -> List("aka","Akan"),
	"am" -> List("amh","Amharic"),
	"ar" -> List("ara","Arabic"),
	"an" -> List("arg","Aragonese"),
	"as" -> List("asm","Assamese"),
	"av" -> List("ava","Avaric"),
	"ae" -> List("ave","Avestan"),
	"ay" -> List("aym","Aymara"),
	"az" -> List("aze","Azerbaijani"),
	"ba" -> List("bak","Bashkir"),
	"bm" -> List("bam","Bambara"),
	"be" -> List("bel","Belarusian"),
	"bn" -> List("ben","Bengali"),
	"bi" -> List("bis","Bislama"),
	"bo" -> List("bod","Tibetan"),
	"bs" -> List("bos","Bosnian"),
	"br" -> List("bre","Breton"),
	"bg" -> List("bul","Bulgarian"),
	"ca" -> List("cat","Catalan"),
	"cs" -> List("ces","Czech"),
	"ch" -> List("cha","Chamorro"),
	"ce" -> List("che","Chechen"),
	"cu" -> List("chu","Church Slavic"),
	"cv" -> List("chv","Chuvash"),
	"kw" -> List("cor","Cornish"),
	"co" -> List("cos","Corsican"),
	"cr" -> List("cre","Cree"),
	"cy" -> List("cym","Welsh"),
	"da" -> List("dan","Danish"),
	"de" -> List("deu","German"),
	"dv" -> List("div","Dhivehi"),
	"dz" -> List("dzo","Dzongkha"),
	"el" -> List("ell","Modern Greek (1453-)"),
	"en" -> List("eng","English"),
	"eo" -> List("epo","Esperanto"),
	"et" -> List("est","Estonian"),
	"eu" -> List("eus","Basque"),
	"ee" -> List("ewe","Ewe"),
	"fo" -> List("fao","Faroese"),
	"fa" -> List("fas","Persian"),
	"fj" -> List("fij","Fijian"),
	"fi" -> List("fin","Finnish"),
	"fr" -> List("fra","French"),
	"fy" -> List("fry","Western Frisian"),
	"ff" -> List("ful","Fulah"),
	"gd" -> List("gla","Scottish Gaelic"),
	"ga" -> List("gle","Irish"),
	"gl" -> List("glg","Galician"),
	"gv" -> List("glv","Manx"),
	"gn" -> List("grn","Guarani"),
	"gu" -> List("guj","Gujarati"),
	"ht" -> List("hat","Haitian"),
	"ha" -> List("hau","Hausa"),
	"sh" -> List("hbs","Serbo-Croatian"),
	"he" -> List("heb","Hebrew"),
	"hz" -> List("her","Herero"),
	"hi" -> List("hin","Hindi"),
	"ho" -> List("hmo","Hiri Motu"),
	"hr" -> List("hrv","Croatian"),
	"hu" -> List("hun","Hungarian"),
	"hy" -> List("hye","Armenian"),
	"ig" -> List("ibo","Igbo"),
	"io" -> List("ido","Ido"),
	"ii" -> List("iii","Sichuan Yi"),
	"iu" -> List("iku","Inuktitut"),
	"ie" -> List("ile","Interlingue"),
	"ia" -> List("ina","Interlingua (International Auxiliary Language Association)"),
	"id" -> List("ind","Indonesian"),
	"ik" -> List("ipk","Inupiaq"),
	"is" -> List("isl","Icelandic"),
	"it" -> List("ita","Italian"),
	"jv" -> List("jav","Javanese"),
	"ja" -> List("jpn","Japanese"),
	"kl" -> List("kal","Kalaallisut"),
	"kn" -> List("kan","Kannada"),
	"ks" -> List("kas","Kashmiri"),
	"ka" -> List("kat","Georgian"),
	"kr" -> List("kau","Kanuri"),
	"kk" -> List("kaz","Kazakh"),
	"km" -> List("khm","Central Khmer"),
	"ki" -> List("kik","Kikuyu"),
	"rw" -> List("kin","Kinyarwanda"),
	"ky" -> List("kir","Kirghiz"),
	"kv" -> List("kom","Komi"),
	"kg" -> List("kon","Kongo"),
	"ko" -> List("kor","Korean"),
	"kj" -> List("kua","Kuanyama"),
	"ku" -> List("kur","Kurdish"),
	"lo" -> List("lao","Lao"),
	"la" -> List("lat","Latin"),
	"lv" -> List("lav","Latvian"),
	"li" -> List("lim","Limburgan"),
	"ln" -> List("lin","Lingala"),
	"lt" -> List("lit","Lithuanian"),
	"lb" -> List("ltz","Luxembourgish"),
	"lu" -> List("lub","Luba-Katanga"),
	"lg" -> List("lug","Ganda"),
	"mh" -> List("mah","Marshallese"),
	"ml" -> List("mal","Malayalam"),
	"mr" -> List("mar","Marathi"),
	"mk" -> List("mkd","Macedonian"),
	"mg" -> List("mlg","Malagasy"),
	"mt" -> List("mlt","Maltese"),
	"mn" -> List("mon","Mongolian"),
	"mi" -> List("mri","Maori"),
	"ms" -> List("msa","Malay (macrolanguage)"),
	"my" -> List("mya","Burmese"),
	"na" -> List("nau","Nauru"),
	"nv" -> List("nav","Navajo"),
	"nr" -> List("nbl","South Ndebele"),
	"nd" -> List("nde","North Ndebele"),
	"ng" -> List("ndo","Ndonga"),
	"ne" -> List("nep","Nepali (macrolanguage)"),
	"nl" -> List("nld","Dutch"),
	"nn" -> List("nno","Norwegian Nynorsk"),
	"nb" -> List("nob","Norwegian Bokmål"),
	"no" -> List("nor","Norwegian"),
	"ny" -> List("nya","Nyanja"),
	"oc" -> List("oci","Occitan (post 1500)"),
	"oj" -> List("oji","Ojibwa"),
	"or" -> List("ori","Oriya (macrolanguage)"),
	"om" -> List("orm","Oromo"),
	"os" -> List("oss","Ossetian"),
	"pa" -> List("pan","Panjabi"),
	"pi" -> List("pli","Pali"),
	"pl" -> List("pol","Polish"),
	"pt" -> List("por","Portuguese"),
	"ps" -> List("pus","Pushto"),
	"qu" -> List("que","Quechua"),
	"rm" -> List("roh","Romansh"),
	"ro" -> List("ron","Romanian"),
	"rn" -> List("run","Rundi"),
	"ru" -> List("rus","Russian"),
	"sg" -> List("sag","Sango"),
	"sa" -> List("san","Sanskrit"),
	"si" -> List("sin","Sinhala"),
	"sk" -> List("slk","Slovak"),
	"sl" -> List("slv","Slovenian"),
	"se" -> List("sme","Northern Sami"),
	"sm" -> List("smo","Samoan"),
	"sn" -> List("sna","Shona"),
	"sd" -> List("snd","Sindhi"),
	"so" -> List("som","Somali"),
	"st" -> List("sot","Southern Sotho"),
	"es" -> List("spa","Spanish"),
	"sq" -> List("sqi","Albanian"),
	"sc" -> List("srd","Sardinian"),
	"sr" -> List("srp","Serbian"),
	"ss" -> List("ssw","Swati"),
	"su" -> List("sun","Sundanese"),
	"sw" -> List("swa","Swahili (macrolanguage)"),
	"sv" -> List("swe","Swedish"),
	"ty" -> List("tah","Tahitian"),
	"ta" -> List("tam","Tamil"),
	"tt" -> List("tat","Tatar"),
	"te" -> List("tel","Telugu"),
	"tg" -> List("tgk","Tajik"),
	"tl" -> List("tgl","Tagalog"),
	"th" -> List("tha","Thai"),
	"ti" -> List("tir","Tigrinya"),
	"to" -> List("ton","Tonga (Tonga Islands)"),
	"tn" -> List("tsn","Tswana"),
	"ts" -> List("tso","Tsonga"),
	"tk" -> List("tuk","Turkmen"),
	"tr" -> List("tur","Turkish"),
	"tw" -> List("twi","Twi"),
	"ug" -> List("uig","Uighur"),
	"uk" -> List("ukr","Ukrainian"),
	"ur" -> List("urd","Urdu"),
	"uz" -> List("uzb","Uzbek"),
	"ve" -> List("ven","Venda"),
	"vi" -> List("vie","Vietnamese"),
	"vo" -> List("vol","Volapük"),
	"wa" -> List("wln","Walloon"),
	"wo" -> List("wol","Wolof"),
	"xh" -> List("xho","Xhosa"),
	"yi" -> List("yid","Yiddish"),
	"yo" -> List("yor","Yoruba"),
	"za" -> List("zha","Zhuang"),
	"zh" -> List("zho","Chinese"),
	"zu" -> List("zul","Zulu")
  )
  
  val ThreePartLangCodesMap = Map(
	"aar" -> "aa","abk" -> "ab","afr" -> "af","aka" -> "ak","amh" -> "am",
	"ara" -> "ar","arg" -> "an","asm" -> "as","ava" -> "av","ave" -> "ae",
	"aym" -> "ay","aze" -> "az","bak" -> "ba","bam" -> "bm","bel" -> "be",
	"ben" -> "bn","bis" -> "bi","bod" -> "bo","bos" -> "bs","bre" -> "br",
	"bul" -> "bg","cat" -> "ca","ces" -> "cs","cha" -> "ch","che" -> "ce",
	"chu" -> "cu","chv" -> "cv","cor" -> "kw","cos" -> "co","cre" -> "cr",
	"cym" -> "cy","dan" -> "da","deu" -> "de","div" -> "dv","dzo" -> "dz",
	"ell" -> "el","eng" -> "en","epo" -> "eo","est" -> "et","eus" -> "eu",
	"ewe" -> "ee","fao" -> "fo","fas" -> "fa","fij" -> "fj","fin" -> "fi",
	"fra" -> "fr","fry" -> "fy","ful" -> "ff","gla" -> "gd","gle" -> "ga",
	"glg" -> "gl","glv" -> "gv","grn" -> "gn","guj" -> "gu","hat" -> "ht",
	"hau" -> "ha","hbs" -> "sh","heb" -> "he","her" -> "hz","hin" -> "hi",
	"hmo" -> "ho","hrv" -> "hr","hun" -> "hu","hye" -> "hy","ibo" -> "ig",
	"ido" -> "io","iii" -> "ii","iku" -> "iu","ile" -> "ie","ina" -> "ia",
	"ind" -> "id","ipk" -> "ik","isl" -> "is","ita" -> "it","jav" -> "jv",
	"jpn" -> "ja","kal" -> "kl","kan" -> "kn","kas" -> "ks","kat" -> "ka",
	"kau" -> "kr","kaz" -> "kk","khm" -> "km","kik" -> "ki","kin" -> "rw",
	"kir" -> "ky","kom" -> "kv","kon" -> "kg","kor" -> "ko","kua" -> "kj",
	"kur" -> "ku","lao" -> "lo","lat" -> "la","lav" -> "lv","lim" -> "li",
	"lin" -> "ln","lit" -> "lt","ltz" -> "lb","lub" -> "lu","lug" -> "lg",
	"mah" -> "mh","mal" -> "ml","mar" -> "mr","mkd" -> "mk","mlg" -> "mg",
	"mlt" -> "mt","mon" -> "mn","mri" -> "mi","msa" -> "ms","mya" -> "my",
	"nau" -> "na","nav" -> "nv","nbl" -> "nr","nde" -> "nd","ndo" -> "ng",
	"nep" -> "ne","nld" -> "nl","nno" -> "nn","nob" -> "nb","nor" -> "no",
	"nya" -> "ny","oci" -> "oc","oji" -> "oj","ori" -> "or","orm" -> "om",
	"oss" -> "os","pan" -> "pa","pli" -> "pi","pol" -> "pl","por" -> "pt",
	"pus" -> "ps","que" -> "qu","roh" -> "rm","ron" -> "ro","run" -> "rn",
	"rus" -> "ru","sag" -> "sg","san" -> "sa","sin" -> "si","slk" -> "sk",
	"slv" -> "sl","sme" -> "se","smo" -> "sm","sna" -> "sn","snd" -> "sd",
	"som" -> "so","sot" -> "st","spa" -> "es","sqi" -> "sq","srd" -> "sc",
	"srp" -> "sr","ssw" -> "ss","sun" -> "su","swa" -> "sw","swe" -> "sv",
	"tah" -> "ty","tam" -> "ta","tat" -> "tt","tel" -> "te","tgk" -> "tg",
	"tgl" -> "tl","tha" -> "th","tir" -> "ti","ton" -> "to","tsn" -> "tn",
	"tso" -> "ts","tuk" -> "tk","tur" -> "tr","twi" -> "tw","uig" -> "ug",
	"ukr" -> "uk","urd" -> "ur","uzb" -> "uz","ven" -> "ve","vie" -> "vi",
	"vol" -> "vo","wln" -> "wa","wol" -> "wo","xho" -> "xh","yid" -> "yi",
	"yor" -> "yo","zha" -> "za","zho" -> "zh","zul" -> "zu"
  )
  
  def upgradeLangCode(code:String) : Option[String] = {
    val response = TwoPartLangCodesMap.get(code)
	if (response == None) None
	else Some(response.get(0))	  
  }
  
  def downgradeLangCode(code:String) : Option[String] = {
	ThreePartLangCodesMap.get(code)
  }
  
  def getLanguage(code:String) : Option[String] = {
    if (code.length == 2) {
      val response = TwoPartLangCodesMap.get(code)
	  if (response == None) None
	  else Some(response.get(1))
    } else if (code.length == 3) {
	  val response = ThreePartLangCodesMap.get(code)
	  if (response == None) None
	  else getLanguage(response.get)
    } else None
	  
  }
}
  